---
# file: playbook.yml

- hosts: production
  roles:
    - operating-system
    - ssh

- hosts: database
  roles:
    - database-mysql
    - database-postgresql

- hosts: app
  roles:
    - app-docker
    - app-phpfpm

- hosts: web
  roles:
    - web-nginx
    - web-haproxy
